-- Skills de Abogados (AI Legal Skills MX v1.0.0) — insertar en tabla projects
-- Tier 1 (01-03): gratis, descargables directamente desde el sitio
-- Tier 2-5 (04-14): requieren registro/login en la Boveda (sin download_url)

insert into projects (title, description, long_description, category, tech_stack, demo_url, repo_url, download_url, featured, is_free, price_cents, thumbnail_url)
values
('Calculadora de Plazos Procesales (MX)', 'Skill para Claude: cómputo de plazos y términos procesales en derecho mexicano (civil, familiar, mercantil, laboral, amparo).', 'Especialista en cómputo de plazos y términos procesales del derecho mexicano. Calcula vencimientos, días hábiles/naturales, suspensiones e interrupciones, con checklist anti-alucinación y fundamento legal.', 'legal', array['Claude','Skill','Derecho México','Tier 1'], null, null, '/skills/legal/01-plazos-procesales.md', true, true, 0, null),

('Redactor de Escritos Procesales (MX)', 'Skill para Claude: redacción de escritos procesales con formato de tribunal mexicano (Proemio, Hechos, Derecho, Puntos Petitorios).', 'Redactor de Escritos Procesales con formato tribunal mexicano. Produce escritos con estructura Proemio → Hechos → Derecho → Puntos Petitorios. Versión preliminar — contenido completo próximamente.', 'legal', array['Claude','Skill','Derecho México','Tier 1'], null, null, '/skills/legal/02-escritos-procesales.md', false, true, 0, null),

('Consultor de Notificaciones y Actuaciones (MX)', 'Skill para Claude: análisis de notificaciones y actuaciones judiciales en materia civil, familiar, mercantil, laboral y amparo.', 'Consultor de Notificaciones y Actuaciones — Derecho Mexicano. Versión preliminar — contenido completo próximamente.', 'legal', array['Claude','Skill','Derecho México','Tier 1'], null, null, '/skills/legal/03-notificaciones-actuaciones.md', false, true, 0, null),

('Analizador de Competencia y Vía Procesal (MX)', 'Skill para Claude: determina competencia (fuero, materia, territorio) y la vía procesal correcta en derecho mexicano.', 'Analizador de Competencia y Vía Procesal — Derecho Mexicano. Determina fuero federal/local, competencia material y territorial, y recomienda la vía procesal (ordinaria, oral, ejecutiva, amparo, etc.).', 'legal', array['Claude','Skill','Derecho México','Tier 2'], null, null, null, false, false, 0, null),

('Checklist de Demanda Inicial (MX)', 'Skill para Claude: revisa demandas judiciales mexicanas y detecta omisiones que generan prevenciones o desechamientos.', 'Checklist de Demanda Inicial — Derecho Mexicano. Revisa requisitos formales y de fondo (civil, familiar, mercantil, laboral, amparo) y entrega un diagnóstico con deficiencias críticas y preventivas.', 'legal', array['Claude','Skill','Derecho México','Tier 2'], null, null, null, false, false, 0, null),

('Redactor de Alegatos y Conclusiones (MX)', 'Skill para Claude: redacción de alegatos de bien probado y conclusiones para el cierre de juicios mexicanos.', 'Redactor de Alegatos y Conclusiones — Derecho Mexicano. Analiza carga probatoria, valora pruebas por tipo y construye el silogismo jurídico de cierre con puntos petitorios.', 'legal', array['Claude','Skill','Derecho México','Tier 2'], null, null, null, false, false, 0, null),

('Generador de Ofrecimiento de Pruebas (MX)', 'Skill para Claude: estrategia y redacción del ofrecimiento de pruebas (documental, testimonial, pericial, etc.) en juicios mexicanos.', 'Generador de Ofrecimiento de Pruebas — Derecho Mexicano. Mapea hechos a probar contra medios de prueba disponibles, anticipa objeciones y redacta el escrito de ofrecimiento.', 'legal', array['Claude','Skill','Derecho México','Tier 2'], null, null, null, false, false, 0, null),

('Consultor de Prescripción y Caducidad (MX)', 'Skill para Claude: analiza si una acción ya prescribió o si operó la caducidad de la instancia en derecho mexicano.', 'Consultor de Prescripción y Caducidad — Derecho Mexicano. Calcula plazos de prescripción por materia (civil, mercantil, laboral), interrupciones/suspensiones y caducidad de instancia.', 'legal', array['Claude','Skill','Derecho México','Tier 3'], null, null, null, false, false, 0, null),

('Redactor de Convenios y Transacciones Judiciales (MX)', 'Skill para Claude: redacción de convenios de pago, divorcio, liquidación laboral y transacciones judiciales en México.', 'Redactor de Convenios y Transacciones Judiciales — Derecho Mexicano. Genera borradores de convenios (pago, divorcio, alimentos, liquidación laboral) con cláusulas y requisitos de ratificación por materia.', 'legal', array['Claude','Skill','Derecho México','Tier 3'], null, null, null, false, false, 0, null),

('Analizador de Excepciones y Defensas (MX)', 'Skill para Claude: identifica excepciones procesales y defensas de fondo aplicables al contestar una demanda en México.', 'Analizador de Excepciones y Defensas — Derecho Mexicano. Cataloga excepciones dilatorias y perentorias, evalúa reconvención y entrega estrategia defensiva con fundamento.', 'legal', array['Claude','Skill','Derecho México','Tier 3'], null, null, null, false, false, 0, null),

('Analizador de Procedencia de Amparo (MX)', 'Skill para Claude: analiza procedencia, tipo de amparo (directo/indirecto), interés jurídico y suspensión del acto reclamado.', 'Analizador de Procedencia y Actos Reclamados — Juicio de Amparo Mexicano. Determina amparo directo/indirecto, tribunal competente, plazos, interés jurídico/legítimo, causales de improcedencia y suspensión.', 'legal', array['Claude','Skill','Derecho México','Amparo','Tier 4'], null, null, null, false, false, 0, null),

('Redactor de Conceptos de Violación (Amparo MX)', 'Skill para Claude: redacta conceptos de violación con silogismo constitucional para demandas de amparo.', 'Redactor de Conceptos de Violación — Juicio de Amparo Mexicano. Construye conceptos de violación con estructura premisa mayor/menor/conclusión/efecto, evitando causas de inoperancia.', 'legal', array['Claude','Skill','Derecho México','Amparo','Tier 4'], null, null, null, false, false, 0, null),

('Calculadora de Liquidaciones y Finiquitos LFT (MX)', 'Skill para Claude: calcula liquidaciones, finiquitos e indemnizaciones laborales conforme a la LFT (UMA/SM 2026).', 'Calculadora de Liquidaciones y Finiquitos LFT — México. Calcula SDI, indemnización constitucional, prima de antigüedad, aguinaldo y vacaciones proporcionales con valores UMA/SM vigentes 2026.', 'legal', array['Claude','Skill','Derecho México','Laboral','Tier 5'], null, null, null, false, false, 0, null),

('Analizador de Relación Laboral y Subordinación (MX)', 'Skill para Claude: analiza si existe relación laboral y presunción de subordinación, incluyendo outsourcing y plataformas digitales.', 'Analizador de Relación Laboral y Presunción de Subordinación — México. Evalúa elementos del Art. 20-21 LFT, señales de simulación, régimen de subcontratación 2021 y carga probatoria ante el TCJA.', 'legal', array['Claude','Skill','Derecho México','Laboral','Tier 5'], null, null, null, false, false, 0, null);
